#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to install
# nginx using listening port 80 that returns a page that
# contains the string `Hello World` when querying at its
# root `/`.
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html

yt="https://www.youtube.com/watch?v=QH2-TGUlwu4"
old_loc="^        location / {"
new_loc="        location /redirect_me {\n                return 301 $yt;\n        }\n\n        location / {"
sudo sed -i "s|$old_loc|$new_loc|" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
