#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to install
# nginx using listening port 80 that returns a page that
# contains the string `Hello World` when querying at its
# root `/`.
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html

old_loc="^\tlocation / {"
new_loc="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s|$old_loc|$new_loc|" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_loc="\terror_page 404 /404.html;\n\n\tlocation / {"
sudo sed -i "s|$old_loc|$new_loc|" /etc/nginx/sites-available/default

sudo service nginx restart
