#!/usr/bin/env bash
# Installs and configures HAProxy on a server

# Install HAProxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Add to /etc/haproxy/haproxy.conf
fe="frontend main\n\tbind *:80\n\tdefault_backend web_servers\n\n"
be="backend web_servers\n\tbalance roundrobin\n\tserver 4928-web-01 34.230.11.150\n\tserver 4928-web-02 3.85.44.226\n"
echo -e "\n\n$fe$be" | sudo tee -a /etc/haproxy/haproxy.conf

sudo service haproxy start
